module.exports.places = [
  "Mumbai	Maharashtra",
  "Delhi	Delhi",
  "Bangalore	Karnataka",
  "Hyderabad	Andhra Pradesh",
  "Ahmedabad	Gujarat",
  "Chennai	Tamil Nadu",
  "Kolkata	West Bengal",
  "Surat	Gujarat",
  "Pune	Maharashtra",
  "Jaipur	Rajasthan",
  "Lucknow	Uttar Pradesh",
  "Kanpur	Uttar Pradesh",
  "Nagpur	Maharashtra",
  "Indore	Madhya Pradesh",
  "Thane	Maharashtra",
  "Bhopal	Madhya Pradesh",
  "Visakhapatnam	Andhra Pradesh",
  "Pimpri and Chinchwad	Maharashtra",
  "Patna	Bihar",
  "Vadodara	Gujarat",
  "Ghaziabad	Uttar Pradesh",
  "Ludhiana	Punjab",
  "Agra	Uttar Pradesh",
  "Nashik	Maharashtra",
  "Faridabad	Haryana",
  "Meerut	Uttar Pradesh",
  "Rajkot	Gujarat",
  "Kalyan and Dombivali	Maharashtra",
  "Vasai Virar	Maharashtra",
  "Varanasi",
];
module.exports.descriptors = [
  "Forest",
  "Ancient",
  "Petrified",
  "Roaring",
  "Cascade",
  "Tumbling",
  "Silent",
  "Redwood",
  "Bullfrog",
  "Maple",
  "Misty",
  "Elk",
  "Grizzly",
  "Ocean",
  "Sea",
  "Sky",
  "Dusty",
  "Diamond",
];

